### ISSUE TITLE
Things to consider

### ISSUE THREAD

**Issue by fazibear** [madeinussr/exop#1]
I have few things that we can consider:

1) Use `vex` instead of custom validation code
2) Always return two element tuple`{:ok, result}` or `{:error, "message"}` or `{:error, {:validation, {...}}`
3) Add option to return validation error when there are unknown parameters
4) Add function to filter params that are provided

What do you think ?

**Comment by madeinussr** [comment]
Thanks for your attention paid to this repo.

1) I considered `vex` usage instead of writing validations on my own, but didn't see implementations for `exop`'s `inner` and `struct` validations. Mb some validations should stay as-is and some - wrap `vex`'s validations. While considering, it worth to think about the cost/profit balance of such integration.
2) Definitely, validation has to return 'unified' tuples. (Will look closer a bit later at this, thanks)
3) What do you mean here? I've been assuming that `contract` doesn't reject 'unknown' parameters, but just validates defined. It's not necessarily to fail validation on parameters which `contract` doesn't know about.
4) Do you mean some kind of custom validation function? It is a good point. Worth to implement and it will not take much time.

**Comment by fazibear** [comment]
About last 2 points, example:

For example we have operation CreateUser.

We passing params from web request to this operation. And operation after validation will pass it to database. Everything is fine for defined parameters, but user can pass additional parameters for example %{authorized: true} witch is bad.

So we can resolve this problem in 2 ways: 

- (this is what point 3 is about) Reject if there are additional parameter
- (this is what point 4 is about) Before I pass params to database I should filter params for example declared(params), and this function will filter out all parameters that in not included in contract.

**Comment by madeinussr** [comment]
So, I've figured out what did you mean on point #3, but I'm not sure I understood your approach with 'filtering' function. At the moment I think additional macro will make sense. This macro will either reject params that were not defined in a contract or not. (Default behavior - do not filter/reject additional params)
Something like this:

```elixir
defmodule IntegersDivision do
  use Exop.Operation

  reject_undefined!

  parameter :a, type: :integer, default: 1

  def process(contract), do: :nothing
end
```

m?

**Comment by fazibear** [comment]
That's exactly what i need. 
About point #4, check out grape declared method: https://github.com/ruby-grape/grape#declared.
I was talking about something similar that will filter out all keys that not appear in contract.

**Comment by madeinussr** [comment]
Hm, thank you for sharing with me Grape's `declared`. I'll consider both approaches (both macros: `reject_undefined!` and `defined\declared`) and create related issues to each accepted thing you've proposed and will try to implement it in next days (lack of spare time on work week, you know).

PS: Grape's `declared` seems more flexible. 'cause this will not restrict my first assumption and will meet your expectations.
