### ISSUE TITLE
Handling lists with data structures inside

### ISSUE THREAD

**Issue by johnhamelink** [madeinussr/exop#14]
Hi there, thanks for making Exop!

I'm trying to establish how best to implement parameter validations for lists of Maps like so:

```
addresses: [
  %{
    line_1: "lorem",
    line_2: "ipsum",
    town: "dolor",
    postcode: "etc..."
  },
  %{
    line_1: "lorem",
    line_2: "ipsum",
    town: "dolor",
    postcode: "etc..."
  }
]
```

It'd be nice if the `:inner` option supported lists, but the docs say it only supports Maps and Keywords?

Thanks!

**Comment by madeinussr** [comment]
Hi @johnhamelink ,

thank you for your proposition.

You're right, at the moment the `inner` check is applicable for either a Map or a Keywords list.
With `inner` check you define a contract for a Map/Keyword, that is: you describe your expectation on that Map/Keyword element(-s).

For a list with any type of an item we should implement another check, because you can't define checks to a particular item within the list.

At the moment I suggest you to try out `func` check: https://github.com/madeinussr/exop#func

You'll have to write some code here and implement the validation/check you want, but it is the most customisable check.

Anyway, I'll take a closer look into this next weekend and figure out: is there a need to implement built-in check for such case.

Thank you.

**Comment by johnhamelink** [comment]
Hi @madeinussr,

Thanks for this - I am currently doing some very naiive and simple validation of the contents of those lists. I look forward to hearing your findings next week: if you agree it would make a good addition I'd be happy to help produce a PR to give us the ability to do this, but I'd like to hear how you think it should work so I can produce a good solution that you can accept 😄

**Comment by madeinussr** [comment]
Hi, @johnhamelink,

I've made some investigation and here is the result of it: https://github.com/madeinussr/exop/issues/15

**Comment by johnhamelink** [comment]
@madeinussr that all looks sensible. Thanks for designing some tests, that's very helpful! I will have time to work on this in the coming weeks, I will submit a PR around that time.

**Comment by madeinussr** [comment]
@johnhamelink ok, I have already done some implementation, so I know that it is possible :)

Consider `list_item` check implementation based on the `inner` implementation's idea.
Bear in mind during your work: `received_params` always have names (atoms), but in this case with list we don't have any name. So, you need to generate proper `received_params` "on the fly" behind the scene, than pass it further (take a look at the `inner` code).

Good luck!

PS: don't want you to be in rush, but if you'll have some obstacles, just let me know and we'll go with my implementation. :) thank you
