### ISSUE TITLE
coerce_with/1 error tuples ignored

### ISSUE THREAD

**Issue by uberbrodt** [madeinussr/exop#18]
This test case:
```
  defmodule TestExopModule do
    use Exop.Operation

    parameter(:a, type: :integer, coerce_with: &__MODULE__.coerce/1)
    parameter(:b, coerce_with: &__MODULE__.coerce/1)

    def process(params), do: params

    def coerce(1), do: {:error, :some_error}
    def coerce(2), do: 2
  end

  test "TestExop" do
    attrs = %{a: 2, b: 1}
    {:error, err} = TestExopModule.run(attrs)

    assert err == {:error, :some_error}
  end
```

I'm expecting for an error to raise, but instead I'm getting:
```
{:ok, %{a: 2, b: {:error, :some_error}}}
```
Tested against 1.1.0

**Comment by madeinussr** [comment]
Hi @uberbrodt 

thank you for using Exop and reporting.

Could you please confirm that it works properly on [1.1.4](https://github.com/madeinussr/exop/blob/master/CHANGELOG.md#114---20181024) version?

I believe that was fixed in the last version. [Here](https://github.com/madeinussr/exop/blob/master/test/operation_test.exs#L537) is the test case.

Thank you.
