### ISSUE TITLE
coerce_with and func validator each should receive current value first and all params map second

### ISSUE THREAD

**Issue by ppraisethesun** [madeinussr/exop#35]
It is a little confusing that these 2 functions receive arguments in a different order and changing `func` signatures to be consistent across the library would help a lot.

It is also more intuitive to have the value that you work with as a first argument.

**Comment by madeinussr** [comment]
thank you for the feedback, will check it

**Comment by madeinussr** [comment]
I took a look, at `func` & `coerce_with` functions syntax. You're right - there is the difference since `coerce_with` has been updated more frequently and `func` hasn't.
At the moment I'd prefer current `coerce_with` expectations regarding its underlying function arity, arguments order.

Will try to align `func` and `coerce_with` in the next release.
